management:
  endpoints:
    web:
      exposure:
        include : '*'
spring:
  application:
    name: configuration-client
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
zuul:
  routes:
    configuration-client : /configuration-client/** 
